name: kubectl-kruise config set-cluster
synopsis: Set a cluster entry in kubeconfig
description: |-
    Set a cluster entry in kubeconfig.

     Specifying a name that already exists will merge new fields on top of existing values for those fields.
usage: kubectl-kruise config set-cluster NAME [--server=server] [--certificate-authority=path/to/certificate/authority] [--insecure-skip-tls-verify=true] [--tls-server-name=example.com]
options:
    - name: certificate-authority
      usage: |
        Path to certificate-authority file for the cluster entry in kubeconfig
    - name: embed-certs
      default_value: "false"
      usage: embed-certs for the cluster entry in kubeconfig
    - name: help
      shorthand: h
      default_value: "false"
      usage: help for set-cluster
    - name: insecure-skip-tls-verify
      default_value: "false"
      usage: insecure-skip-tls-verify for the cluster entry in kubeconfig
    - name: proxy-url
      usage: proxy-url for the cluster entry in kubeconfig
    - name: server
      usage: server for the cluster entry in kubeconfig
    - name: tls-server-name
      usage: tls-server-name for the cluster entry in kubeconfig
inherited_options:
    - name: as
      usage: |
        Username to impersonate for the operation. User could be a regular user or a service account in a namespace.
    - name: as-group
      default_value: '[]'
      usage: |
        Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
    - name: as-uid
      usage: UID to impersonate for the operation.
    - name: cache-dir
      default_value: ${HOME}/.kube/cache
      usage: Default cache directory
    - name: client-certificate
      usage: Path to a client certificate file for TLS
    - name: client-key
      usage: Path to a client key file for TLS
    - name: cluster
      usage: The name of the kubeconfig cluster to use
    - name: context
      usage: The name of the kubeconfig context to use
    - name: kubeconfig
      usage: use a particular kubeconfig file
    - name: match-server-version
      default_value: "false"
      usage: Require server version to match client version
    - name: namespace
      shorthand: "n"
      usage: If present, the namespace scope for this CLI request
    - name: password
      usage: Password for basic authentication to the API server
    - name: profile
      default_value: none
      usage: |
        Name of profile to capture. One of (none|cpu|heap|goroutine|threadcreate|block|mutex)
    - name: profile-output
      default_value: profile.pprof
      usage: Name of the file to write the profile to
    - name: request-timeout
      default_value: "0"
      usage: |
        The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.
    - name: token
      usage: Bearer token for authentication to the API server
    - name: user
      usage: The name of the kubeconfig user to use
    - name: username
      usage: Username for basic authentication to the API server
    - name: warnings-as-errors
      default_value: "false"
      usage: |
        Treat warnings received from the server as errors and exit with a non-zero exit code
example: "  # Set only the server field on the e2e cluster entry without touching other values\n  kubectl config set-cluster e2e --server=https://1.2.3.4\n  \n  # Embed certificate authority data for the e2e cluster entry\n  kubectl config set-cluster e2e --embed-certs --certificate-authority=~/.kube/e2e/kubernetes.ca.crt\n  \n  # Disable cert checking for the e2e cluster entry\n  kubectl config set-cluster e2e --insecure-skip-tls-verify=true\n  \n  # Set custom TLS server name to use for validation for the e2e cluster entry\n  kubectl config set-cluster e2e --tls-server-name=my-cluster-name\n  \n  # Set proxy url for the e2e cluster entry\n  kubectl config set-cluster e2e --proxy-url=https://1.2.3.4"
see_also:
    - kubectl-kruise config - Modify kubeconfig files
