name: kubectl-kruise config
synopsis: Modify kubeconfig files
description: |-
    Modify kubeconfig files using subcommands like "kubectl config set current-context my-context"

     The loading order follows these rules:

      1.  If the --kubeconfig flag is set, then only that file is loaded. The flag may only be set once and no merging takes place.
      2.  If $KUBECONFIG environment variable is set, then it is used as a list of paths (normal path delimiting rules for your system). These paths are merged. When a value is modified, it is modified in the file that defines the stanza. When a value is created, it is created in the first file that exists. If no files in the chain exist, then it creates the last file in the list.
      3.  Otherwise, ${HOME}/.kube/config is used and no merging takes place.
usage: kubectl-kruise config SUBCOMMAND
options:
    - name: help
      shorthand: h
      default_value: "false"
      usage: help for config
    - name: kubeconfig
      usage: use a particular kubeconfig file
inherited_options:
    - name: as
      usage: |
        Username to impersonate for the operation. User could be a regular user or a service account in a namespace.
    - name: as-group
      default_value: '[]'
      usage: |
        Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
    - name: as-uid
      usage: UID to impersonate for the operation.
    - name: cache-dir
      default_value: ${HOME}/.kube/cache
      usage: Default cache directory
    - name: certificate-authority
      usage: Path to a cert file for the certificate authority
    - name: client-certificate
      usage: Path to a client certificate file for TLS
    - name: client-key
      usage: Path to a client key file for TLS
    - name: cluster
      usage: The name of the kubeconfig cluster to use
    - name: context
      usage: The name of the kubeconfig context to use
    - name: insecure-skip-tls-verify
      default_value: "false"
      usage: |
        If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
    - name: match-server-version
      default_value: "false"
      usage: Require server version to match client version
    - name: namespace
      shorthand: "n"
      usage: If present, the namespace scope for this CLI request
    - name: password
      usage: Password for basic authentication to the API server
    - name: profile
      default_value: none
      usage: |
        Name of profile to capture. One of (none|cpu|heap|goroutine|threadcreate|block|mutex)
    - name: profile-output
      default_value: profile.pprof
      usage: Name of the file to write the profile to
    - name: request-timeout
      default_value: "0"
      usage: |
        The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.
    - name: server
      shorthand: s
      usage: The address and port of the Kubernetes API server
    - name: tls-server-name
      usage: |
        Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
    - name: token
      usage: Bearer token for authentication to the API server
    - name: user
      usage: The name of the kubeconfig user to use
    - name: username
      usage: Username for basic authentication to the API server
    - name: warnings-as-errors
      default_value: "false"
      usage: |
        Treat warnings received from the server as errors and exit with a non-zero exit code
see_also:
    - kubectl-kruise - kubectl-kruise controls the OpenKruise CRs
    - kubectl-kruise config current-context - Display the current-context
    - kubectl-kruise config delete-cluster - Delete the specified cluster from the kubeconfig
    - kubectl-kruise config delete-context - Delete the specified context from the kubeconfig
    - kubectl-kruise config delete-user - Delete the specified user from the kubeconfig
    - kubectl-kruise config get-clusters - Display clusters defined in the kubeconfig
    - kubectl-kruise config get-contexts - Describe one or many contexts
    - kubectl-kruise config get-users - Display users defined in the kubeconfig
    - kubectl-kruise config rename-context - Rename a context from the kubeconfig file
    - kubectl-kruise config set - Set an individual value in a kubeconfig file
    - kubectl-kruise config set-cluster - Set a cluster entry in kubeconfig
    - kubectl-kruise config set-context - Set a context entry in kubeconfig
    - kubectl-kruise config set-credentials - Set a user entry in kubeconfig
    - kubectl-kruise config unset - Unset an individual value in a kubeconfig file
    - kubectl-kruise config use-context - Set the current-context in a kubeconfig file
    - kubectl-kruise config view - Display merged kubeconfig settings or a specified kubeconfig file
